### ISSUE TITLE
needed to install ejs before node would run

### ISSUE THREAD

**Issue by IanMulvany** [elifesciences/lens#114]
node server

module.js:340
    throw err;
          ^
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ian/workbench/lens-next/lens-starter/server.js:6:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
➜  lens-starter git:(master) git pull
Already up-to-date.
➜  lens-starter git:(master) npm install ejs
npm WARN package.json ams-lens@1.0.0 No repository field.
npm http GET https://registry.npmjs.org/ejs
npm http 200 https://registry.npmjs.org/ejs
npm http GET https://registry.npmjs.org/ejs/-/ejs-2.1.4.tgz
npm http 200 https://registry.npmjs.org/ejs/-/ejs-2.1.4.tgz
ejs@2.1.4 node_modules/ejs
➜  lens-starter git:(master) node server
Lens running on port 4001
http://127.0.0.1:4001/

**Comment by michael** [comment]
Mhh.. this should be automatically done when you execute `substance --update`. Not sure why it doesn't work. I will add to the documentation an extra line: 

`$ npm install`

so we can be sure these dev dependencies are installed.
