### ISSUE TITLE
[lens-starter] npm start fails

### ISSUE THREAD

**Issue by pkra** [elifesciences/lens#163]
A fresh clone of lens-starter (or AMS-lens) fails to `npm start` right now. I'm guessing some dependencies have changed?

```bash
$ npm start

> lens-starter@2.0.0 start /tmp/lens-starter
> node server.js

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4001
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at Server.listen (net.js:1368:5)
    at Object.<anonymous> (/tmp/lens-starter/server.js:68:24)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "XXXXXX/node/v5.5.0/bin/node" "XXXXXX/node/v5.5.0/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! lens-starter@2.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lens-starter@2.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lens-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lens-starter
npm ERR! There is likely additional logging output above.
```

**Comment by pkra** [comment]
Luckily, I'm just stupid. Sorry for the noise. I had another server running on a different console..
